name: Build and Deploy Golang Hello App

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hello-cluster    # TODO: update to cluster name
  GKE_ZONE: asia-southeast2-a   # TODO: update to cluster zone
  DEPLOYMENT_NAME: helloweb # TODO: update to deployment name
  IMAGE: hello-app
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup gcloud cli
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      # Login Dockerhub      
      - uses: actions/checkout@v2
      - name: Docker login
        run: |-
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "$DOCKER_USER/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$DOCKER_USER/$IMAGE:$GITHUB_SHA"

      # Deploy to GKE
      - name: Deploy
        run: |-
          cd manifests
          pwd   
          touch kube-config
          echo $KUBE_CONFIG | base64 -d > kube-config
          ls -la
          sed -i "s/GITHUB_SHA/$GITHUB_SHA/g" helloweb-deployment.yaml
          kubectl apply -f helloweb-deployment.yaml --kubeconfig=kube-config
          kubectl apply -f helloweb-hpa.yaml --kubeconfig=kube-config
          kubectl apply -f helloweb-service-load-balancer.yaml --kubeconfig=kube-config
          kubectl get svc -o wide --kubeconfig=kube-config
